<template>
    <div>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
        <p>switch组件测试</p>
    </div>
</template>

<script lang="ts">
    export default {};
</script>

<style lang="scss" scoped>

</style>